version: "3.7"

services:
  ocelotgateway:
    image: ocelotgateway
    build:
      context: .
      dockerfile: ./samples/OcelotGateway/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    depends_on:
      - weatherserver
      - productserver
      - greetserver
    networks:
      - mynetwork

  weatherserver:
    image: weatherserver
    build:
      context: .
      dockerfile: ./samples/WeatherServer/Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    networks:
      - mynetwork

  productserver:
    image: productserver
    build:
      context: .
      dockerfile: ./samples/ProductGrpcServer/Dockerfile
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    networks:
      - mynetwork

  greetserver:
    image: greetserver
    build:
      context: .
      dockerfile: ./samples/GreatGrpcServer/Dockerfile
    ports:
      - "5003:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    networks:
      - mynetwork

networks:
  mynetwork:
    name: mynetwork-network
